### PR TITLE
Update dependencies

### LINKED ISSUE #148: Update dependencies
* https://david-dm.org/ckeditor/ckeditor5-angular?type=dev
* https://david-dm.org/ckeditor/ckeditor5-angular

image

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Updated dependencies. Added package-lock.json. Closes #148.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by pomek** [comment]
CI is red.

**Comment by ma2ciek** [comment]
> CI is red.

oops. I'll check it.

**Comment by ma2ciek** [comment]
Interestingly I've broken one e2e test.

**Comment by ma2ciek** [comment]
The CI is fixed.

ping @pomek.

**Comment by ma2ciek** [comment]
I'm merging since these changes shouldn't impact library users.

**Pull request merged**
