### PR TITLE
I/235

### LINKED ISSUE #235: Check compatibility with latest Angular (v11)
A similar to CKEditor 4 (https://github.com/ckeditor/ckeditor4-angular/issues/148).

### PR DESCRIPTION
**Pull request by pkwasnik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Added support for Angular 11. Internal: Updated internal Angular deps to v. 11. Closes #235.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by ma2ciek** [comment]
Have you tested it with older Angular apps - e.g. using Angular 9.1?

**Comment by pkwasnik** [comment]
Yes, I've tested it with Angular 9.1.9, 10.1.4 and 11.0.3. There is nothing to change in package.json that `ckeditor5-angular` is build from.

**Comment by pkwasnik** [comment]
Reported regression: angular/angular#40215

PR for documentation update: ckeditor/ckeditor5#8708

**Comment by ma2ciek** [comment]
> Reported regression: [angular/angular#40215](https://github.com/angular/angular/issues/40215)

> PR for documentation update: [ckeditor/ckeditor5#8708](https://github.com/ckeditor/ckeditor5/pull/8708)

Thanks!

**Pull request merged**
