### PR TITLE
Align integration to work with self-service for premium features.

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Align integration to work with self-service for premium features.

---

### Additional information

More details: https://github.com/ckeditor/ckeditor5/issues/17317

### CODE REVIEW

**Review by arkflpc — DISMISSED** [review]

**Review by arkflpc — DISMISSED** [review]

**Review by psmyrek — COMMENTED** [review]
Script for preparing the release (`yarn release:prepare-packages`) modifies one file outside the release directory:

```
$ git status
On branch editor-integration/angular/add-usage-data
Your branch is up to date with 'origin/editor-integration/angular/add-usage-data'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/ckeditor/package.json

no changes added to commit (use "git add" and/or "git commit -a")
```

Also, in the generated release directory, there are two `package.json` files:
- `release/ckeditor5-angular/package.json`
- `release/ckeditor5-angular/esm2022/package.json`

Is it expected?

obraz

**Comment by Mati365** [comment]
@psmyrek :thinking: I'll check that.

**Comment by Mati365** [comment]
@psmyrek This `package.json` was used by ESM import to determine version of integration. You are correct, we can get rid of it, as it may be problematic in older installations.  I updated the release script, as it's quite hard to import `environment` files without compiler changes, and replaced the version during the release process. It minimizes amount of changes in deployment flow.  Can you take a look again?

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Pull request merged**
