### PR TITLE
Use ckeditor5 types in angular component.

### PR DESCRIPTION
**Pull request by mremiszewski**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Migrate package to TypeScript. Closes ckeditor/ckeditor5#13541.

MAJOR BREAKING CHANGE: Integration now requires Editor version 37 or later.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by Reinmar** [comment]
People are waiting https://github.com/ckeditor/ckeditor5/issues/13773 ;)

**Review by psmyrek — APPROVED** [review]
Demo apps in this repository use Angular 13+ and they work fine.
I created a new test app with Angular 15+ that uses changes from this PR and it works too.

So, LGTM 🎉

**Review by pomek — APPROVED** [review]
~LGTM.~

**Review by pomek — CHANGES_REQUESTED** [review]
Typings from CKEditor 5 come with the latest CKEditor 5, which is 37.0.0 at this moment. We cannot use lower versions. 

I will update it.

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
